[package]
name = "rocketbot_barcode"
version = "0.1.0"
edition = "2021"

[dependencies]
datamatrix = { version = "0.3" }
png = { version = "0.17" }
qrcode = { version = "0.13", default-features = false }
