[workspace]
members = [
    "rocketbot",
    "rocketbot_interface",
    "rocketbot_plugin_belch",
    "rocketbot_plugin_config_user_alias",
    "rocketbot_plugin_fortune",
    "rocketbot_plugin_thanks",
]
