[package]
name = "rocketbot_plugin_version"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
libc = { version = "0.2" }
log = { version = "0.4" }
rocketbot_interface = { path = "../rocketbot_interface" }
rustc_version_runtime = { version = "0.2" }
serde_json = { version = "1.0" }
