[package]
name = "rocketbot_plugin_version"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
libc = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
rustc_version_runtime = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
