[package]
name = "rocketbot_plugin_version"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
json = { version = "0.12" }
rocketbot_interface = { path = "../rocketbot_interface" }
tokio = { version = "1.7", features = ["sync"] }
