[package]
name = "rocketbot_plugin_bim"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bigdecimal = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
ciborium = { workspace = true }
once_cell = { workspace = true }
png = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rocketbot_bim_common = { path = "../rocketbot_bim_common" }
rocketbot_interface = { path = "../rocketbot_interface" }
rocketbot_primes = { path = "../rocketbot_primes" }
rocketbot_render_text = { path = "../rocketbot_render_text", features = ["png"] }
rocketbot_string = { path = "../rocketbot_string", features = ["regex", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tokio-postgres = { workspace = true, features = ["with-chrono-0_4"] }
tracing = { workspace = true }

[dev-dependencies]
boa_engine = { workspace = true }
clap = { workspace = true, features = ["derive"] }
csv = { workspace = true }
ego-tree = { workspace = true }
form_urlencoded = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["rustls"] }
rhai = { workspace = true, features = ["serde"] }
rocketbot_mediawiki_parsing = { path = "../rocketbot_mediawiki_parsing" }
scraper = { workspace = true }
sxd-document = { workspace = true }
sxd-xpath = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
url = { workspace = true }
zip = { workspace = true }
