[package]
name = "rocketbot_makepdf"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { workspace = true }
flate2 = { workspace = true }
printpdf = { workspace = true, features = ["jpeg", "png"] }
rustybuzz = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
