[package]
name = "rocketbot_plugin_wienerlinien"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
csv = { version = "1.1" }
form_urlencoded = { version = "1.0" }
hyper = { version = "0.14" }
indexmap = { version = "1.7", features = ["serde-1"] }
log = { version = "0.4" }
regex = { version = "1.5" }
reqwest = { version = "0.11", features = ["rustls-tls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
strsim = { version = "0.10" }
