[package]
name = "rocketbot_plugin_wienerlinien"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
csv = { version = "1.2" }
form_urlencoded = { version = "1.2" }
hyper = { version = "1.6" }
indexmap = { version = "2.10", features = ["serde"] }
regex = { version = "1.11" }
reqwest = { version = "0.12", features = ["rustls-tls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
strsim = { version = "0.11" }
tracing = { version = "0.1" }
