[package]
name = "rocketbot_plugin_vitals"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
num-rational = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
