[package]
name = "rocketbot_plugin_vitals"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
bytes = { version = "1.1" }
chrono = { version = "0.4" }
log = { version = "0.4" }
num-rational = { version = "0.4" }
rand = { version = "0.8" }
reqwest = { version = "0.11", features = ["rustls-tls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
