[package]
name = "rocketbot_plugin_simultype"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
tracing = { workspace = true }
