[package]
name = "rocketbot_plugin_grammargen"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
either = { workspace = true }
num-bigint = { workspace = true, features = ["rand_0_10"] }
num-traits = { workspace = true }
once_cell = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
