[package]
name = "rocketbot_plugin_serious_mode"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
chrono = { version = "0.4" }
log = { version = "0.4" }
once_cell = { version = "1.10" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
