[package]
name = "rocketbot_plugin_date"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
julian = { workspace = true }
once_cell = { workspace = true }
ordered-float = { workspace = true, features = ["serde"] }
rand = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
