[package]
name = "rocketbot_plugin_hackernews"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
md-5 = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
tracing = { workspace = true }
