# Wikidata
SELECT ?alpha3code ?alpha2code ?platecode ?countryLabel
WHERE 
{
  # country is-a sovereign state
  ?country wdt:P31 wd:Q3624078.
  # country has-an alpha-3 code
  ?country wdt:P298 ?alpha3code.
  OPTIONAL {
    # country has-an alpha-2 code
    ?country wdt:P297 ?alpha2code.
    # country has-a license plate code
    ?country wdt:P395 ?platecode.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
