[package]
name = "rocketbot_plugin_transliterate"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
rocketbot_regex_replace = { path = "../rocketbot_regex_replace" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
