[package]
name = "rocketbot_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bitflags = { workspace = true }
chrono = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["client", "client-legacy", "http1", "http2"] }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }
