[package]
name = "rocketbot_interface"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
chrono = { version = "0.4" }
log = { version = "0.4" }
once_cell = { version = "1.8" }
serde_json = { version = "1.0" }
tokio = { version = "1.7", features = ["sync"] }
