[package]
name = "rocketbot_plugin_barcode"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
base45 = { workspace = true }
chrono = { workspace = true }
ciborium = { workspace = true }
flate2 = { workspace = true }
rand = { workspace = true }
rocketbot_barcode = { path = "../rocketbot_barcode" }
rocketbot_interface = { path = "../rocketbot_interface" }
rocketbot_makepdf = { path = "../rocketbot_makepdf" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
unicode-normalization = { workspace = true }
