[package]
name = "rocketbot_plugin_vaccine"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
chrono = { version = "0.4" }
encoding_rs = { version = "0.8" }
log = { version = "0.4" }
num-bigint = { version = "0.4" }
num-traits = { version = "0.2" }
reqwest = { version = "0.11", features = ["rustls-tls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
tokio = { version = "1.7", features = ["sync"] }
