[package]
name = "rocketbot_spelling"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = { version = "0.7" }
log = { version = "0.4" }
once_cell = { version = "1.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[dev-dependencies]
env_logger = { version = "0.9" }
