[package]
name = "rocketbot_spelling"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = { version = "0.8" }
once_cell = { version = "1.21" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tracing = { version = "0.1" }

[dev-dependencies]
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
