[package]
name = "rocketbot_plugin_config_user_alias"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
rocketbot_string = { path = "../rocketbot_string", features = ["regex"] }
serde_json = { workspace = true }
tracing = { workspace = true }
