[package]
name = "rocketbot_plugin_paper"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
once_cell = { version = "1.8" }
regex = { version = "1.5" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
