[package]
name = "rocketbot_plugin_paper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bigdecimal = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
tracing = { workspace = true }
