[package]
name = "rocketbot_plugin_numberword"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
log = { version = "0.4" }
once_cell = { version = "1.9" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
