[package]
name = "rocketbot_plugin_bim_react"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
png = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }
rocketbot_bim_common = { path = "../rocketbot_bim_common" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
