rules = [
    # disqualify URLs
    { find = "://", disqualify = true },

    # disqualify commands
    { find = "^\\s*!", disqualify = true },

    # special case: "Steve" is only one syllable, but "Steven" is two
    { find = "(?i)steven", adjust_count = 2 },
    { find = "(?i)steve" },

    # in "zuerst" etc., "ue" is not a diphthong
    { find = "(?i)zue", replace = "e" },

    # neither is "io" in "mio"
    { find = "(?i)mio", replace = "mi" },

    # approximation of syllabizing -xl (where x is a consonant)
    { find = "(?i)[bdfgkmnpqstvwxz]l\\b" },
    { find = "(?i)[bdfgkmnpqstvwxz]l[bcdfghjklmnpqrstvwxz]" },

    # diphthongs make a syllable
    { find = "(?i)[aeiouyäöü]{2}" },

    # vowels make a syllable
    { find = "(?i)[aeiouyäöü]" },
]
