[package]
name = "rocketbot_plugin_linguistics"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bitflags = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tokio-postgres = { workspace = true, features = ["with-chrono-0_4"] }
tracing = { workspace = true }

[dev-dependencies]
bzip2-rs = { workspace = true }
ego-tree = { workspace = true }
scraper = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
toml = { workspace = true }
zim = { workspace = true }
