[package]
name = "rocketbot_plugin_deobfuscate"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
rocketbot_spelling = { path = "../rocketbot_spelling" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
