[package]
name = "rocketbot_plugin_group_pressure"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
