[package]
name = "rocketbot_plugin_sed"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
once_cell = { workspace = true }
fancy-regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
tracing = { workspace = true }
