[package]
name = "rocketbot_plugin_sed"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
json = { version = "0.12" }
log = { version = "0.4" }
once_cell = { version = "1.8" }
regex = { version = "1.5" }
rocketbot_interface = { path = "../rocketbot_interface" }
tokio = { version = "1.7", features = ["sync"] }
