// This file has been automatically generated from .../rocketbot_plugin_bim/db/achievements.pgsql.
// Manual changes will be lost.


use crate::AchievementDef;


pub static ACHIEVEMENT_DEFINITIONS: [AchievementDef; 70] = [
    AchievementDef::new(1, "Beastly", "Ride a vehicle (of any company) with number 666."),
    AchievementDef::new(22, "Kinda Beastly", "Ride a vehicle (of any company) whose number contains \"666\" (but isn't 666)."),
    AchievementDef::new(2, "Nice", "Ride a vehicle (of any company) with number 69."),
    AchievementDef::new(23, "Rather Nice", "Ride a vehicle (of any company) whose number contains \"69\" (but isn't 69)."),
    AchievementDef::new(4, "Two of a Kind", "Ride a vehicle (of any company) whose number consists of one digit repeated at least twice."),
    AchievementDef::new(5, "Three of a Kind", "Ride a vehicle (of any company) whose number consists of one digit repeated at least three times."),
    AchievementDef::new(6, "Four of a Kind", "Ride a vehicle (of any company) whose number consists of one digit repeated at least four times."),
    AchievementDef::new(7, "Palindrome", "Ride a vehicle (of any company) whose number is a palindrome while not being all the same digit."),
    AchievementDef::new(9, "Boeing", "Ride a vehicle (of any company) whose number has the pattern \"7x7\"."),
    AchievementDef::new(26, "Priming the Pump", "Ride a vehicle (of any company) whose vehicle number is a four-digit prime."),
    AchievementDef::new(27, "Prim and Proper", "Ride a vehicle (of any company) whose vehicle number is a three-digit prime."),
    AchievementDef::new(28, "Primate Representative", "Ride a vehicle (of any company) whose vehicle number is a two-digit prime."),
    AchievementDef::new(29, "Primus Inter Pares", "Ride a vehicle (of any company) whose vehicle number is a single-digit prime."),
    AchievementDef::new(30, "It Gets Better", "Ride a vehicle (of any company) whose at least three-digit number's decimal digits are in ascending order."),
    AchievementDef::new(31, "Downward Spiral", "Ride a vehicle (of any company) whose at least three-digit number's decimal digits are in descending order."),
    AchievementDef::new(3, "Home Line", "Ride a vehicle (of any company) where the vehicle number and the line are the same."),
    AchievementDef::new(8, "Mirror Home Line", "Ride a vehicle (of any company) where the vehicle number is the reverse of the line."),
    AchievementDef::new(24, "Indivisibiliter", "Ride a vehicle (of any company) whose vehicle number is divisible by (but not equal to) its line number."),
    AchievementDef::new(25, "Inseparabiliter", "Ride a vehicle (of any company) on a line whose number is divisible by (but not equal to) the vehicle's number."),
    AchievementDef::new(39, "Continual", "Ride the same vehicle on the same line five times."),
    AchievementDef::new(40, "Repeated", "Ride the same vehicle on the same line ten times."),
    AchievementDef::new(41, "Insistent", "Ride the same vehicle on the same line twenty times."),
    AchievementDef::new(42, "Constant", "Ride the same vehicle on the same line thirty times."),
    AchievementDef::new(43, "Dull", "Ride the same vehicle on the same line fifty times."),
    AchievementDef::new(44, "Boring but Nice", "Ride the same vehicle on the same line sixty-nine times."),
    AchievementDef::new(45, "Ceaseless", "Ride the same vehicle on the same line one hundred times."),
    AchievementDef::new(46, "We Meet Again", "Ride the same vehicle on two different lines."),
    AchievementDef::new(47, "Explorer", "Ride the same vehicle on three different lines."),
    AchievementDef::new(48, "Seen the World", "Ride the same vehicle on five different lines."),
    AchievementDef::new(10, "Elsewhere", "Ride two vehicles with the same vehicle number but different companies."),
    AchievementDef::new(11, "Monthiversary", "Ride the same vehicle on the same day of two consecutive months."),
    AchievementDef::new(12, "Anniversary", "Ride the same vehicle on the same day of two consecutive years."),
    AchievementDef::new(13, "Same Time Next Week", "Ride the same vehicle on the same weekday of two consecutive weeks."),
    AchievementDef::new(32, "Take Five", "Ride the same vehicle five times."),
    AchievementDef::new(33, "Both Hands", "Ride the same vehicle ten times."),
    AchievementDef::new(34, "Fingers and Toes", "Ride the same vehicle twenty times."),
    AchievementDef::new(35, "Flagrant Favoritism", "Ride the same vehicle thirty times."),
    AchievementDef::new(36, "Habitual", "Ride the same vehicle fifty times."),
    AchievementDef::new(37, "Familiarity Is Nice", "Ride the same vehicle sixty-nine times."),
    AchievementDef::new(38, "Common-Law Marriage", "Ride the same vehicle one hundred times."),
    AchievementDef::new(14, "Five Sweep", "Collect rides with five vehicles of the same company with consecutive numbers."),
    AchievementDef::new(49, "Journeyman", "Collect five rides in a day."),
    AchievementDef::new(15, "Ten Sweep", "Collect rides with ten vehicles of the same company with consecutive numbers."),
    AchievementDef::new(50, "Hopper", "Collect ten rides in a day."),
    AchievementDef::new(16, "Twenty Sweep", "Collect rides with twenty vehicles of the same company with consecutive numbers."),
    AchievementDef::new(51, "Serial Tripper", "Collect twenty rides in a day."),
    AchievementDef::new(17, "Thirty Sweep", "Collect rides with thirty vehicles of the same company with consecutive numbers."),
    AchievementDef::new(52, "Single-Stop Vehicle Skipper", "Collect thirty rides in a day."),
    AchievementDef::new(18, "Forty Sweep", "Collect rides with forty vehicles of the same company with consecutive numbers."),
    AchievementDef::new(53, "Too Much Spare Time", "Collect fifty rides in a day."),
    AchievementDef::new(19, "Half-Century Sweep", "Collect rides with fifty vehicles of the same company with consecutive numbers."),
    AchievementDef::new(54, "Commuter", "Collect ten rides in a week."),
    AchievementDef::new(20, "Nice Sweep", "Collect rides with sixty-nine vehicles of the same company with consecutive numbers."),
    AchievementDef::new(55, "Passenger", "Collect twenty rides in a week."),
    AchievementDef::new(21, "Century Sweep", "Collect rides with one hundred vehicles of the same company with consecutive numbers."),
    AchievementDef::new(56, "Enthusiast", "Collect thirty rides in a week."),
    AchievementDef::new(57, "Trainspotter", "Collect fifty rides in a week."),
    AchievementDef::new(58, "Nice Rider", "Collect sixty-nine rides in a week."),
    AchievementDef::new(59, "Trainstopper", "Collect one hundred rides in a week."),
    AchievementDef::new(60, "Two Pow Seven", "Collect one hundred and twenty-eight rides in a week."),
    AchievementDef::new(61, "Pokedex", "Collect one hundred and fifty-one rides in a week."),
    AchievementDef::new(62, "Consistency", "Collect one hundred rides in thirty days."),
    AchievementDef::new(63, "Perseverance", "Collect two hundred rides in thirty days."),
    AchievementDef::new(64, "Frequent Flyer", "Collect three hundred rides in thirty days."),
    AchievementDef::new(65, "No House Required", "Collect five hundred rides in thirty days."),
    AchievementDef::new(66, "Boomer", "Collect two hundred rides in 365 days."),
    AchievementDef::new(67, "GenX", "Collect five hundred rides in 365 days."),
    AchievementDef::new(68, "Millennial", "Collect one thousand rides in 365 days."),
    AchievementDef::new(69, "GenZ", "Collect 1500 rides in 365 days."),
    AchievementDef::new(70, "GenAlpha", "Collect 2000 rides in 365 days."),
];
