[package]
name = "rocketbot_plugin_slogan"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
form_urlencoded = { version = "1.2" }
regex = { version = "1.11" }
reqwest = { version = "0.12", features = ["rustls-tls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
sxd-document = { version = "0.3" }
sxd-xpath = { version = "0.4" }
tracing = { version = "0.1" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
