[package]
name = "rocketbot_plugin_slogan"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
form_urlencoded = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
sxd-document = { workspace = true }
sxd-xpath = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
