[package]
name = "rocketbot_plugin_user_list_message"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
tracing = { version = "0.1" }
