[package]
name = "rocketbot_plugin_time"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
chrono = { version = "0.4" }
chrono-tz = { version = "0.6" }
log = { version = "0.4" }
rocketbot_geocoding = { path = "../rocketbot_geocoding" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { version = "1.0" }
