[package]
name = "rocketbot_plugin_time"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
rocketbot_geocoding = { path = "../rocketbot_geocoding" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde_json = { workspace = true }
tracing = { workspace = true }
