[package]
name = "rocketbot_xlsx"
version = "0.1.0"
edition = "2021"

[dependencies]
from-to-repr = { version = "0.2", features = ["from_to_other"] }
strict-num = { version = "0.2" }
sxd-document = { version = "0.3" }
zip = { version = "2.2" }
