[package]
name = "rocketbot_render_text"
version = "0.1.0"
edition = "2021"

[dependencies]
png = { version = "0.17", optional = true }
swash = { version = "0.1" }

[dev-dependencies]
png = { version = "0.17" }
