[package]
name = "rocketbot_plugin_weather"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { version = "0.1" }
bytes = { version = "1.0" }
chrono = { version = "0.4" }
json = { version = "0.12" }
log = { version = "0.4" }
once_cell = { version = "1.8" }
regex = { version = "1.5" }
reqwest = { version = "0.11", features = ["rustls-tls"] }
rocketbot_geonames = { path = "../rocketbot_geonames" }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1.7" }
