[package]
name = "rocketbot_plugin_elementary"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rocketbot_interface = { path = "../rocketbot_interface" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
unicode-normalization = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["form", "rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
