name: rocketbot build release
on: [push]
jobs:
  build-arch-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git python-toml
      - name: check out repository code
        uses: actions/checkout@v2
      - name: verify no plugin omissions
        run: 'python3 cicd/plugin_check.py'
      - name: update version
        run: 'python3 cicd/version_stamp.py'
      - name: generate TSV grammars
        run: 'python3 cicd/tsv2grammar.py rocketbot_plugin_grammargen/grammars/*.tsv'
      - name: fetch dependencies
        run: sh ./cicd/cargo_fetch.sh
      - name: run release build
        run: cargo build --release
      - name: run release tests
        run: cargo test --release
      - name: generate CountryCodes.json
        run: cargo run --example countrycodes --release
      - name: upload release binary
        uses: actions/upload-artifact@v2
        with:
          name: rocketbot-release
          path: |
            target/release/rocketbot
            target/release/rocketbotweb
            rocketbot_plugin_calc/data/unitdb.toml
            rocketbot_plugin_grammargen/grammars/*.grammar
            rocketbotweb/static/*
            rocketbotweb/templates/*.tera
            CountryCodes.json
