name: rocketbot build release
on: [push]
jobs:
  build-arch-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git python-toml
      - name: check out repository code
        uses: actions/checkout@v2
      - name: verify no plugin omissions
        run: 'python3 cicd/plugincheck.py'
      - name: update version
        run: 'sed -i -e "s/{{VERSION}}/`git rev-parse HEAD`/" rocketbot_plugin_version/src/lib.rs'
      - name: fetch dependencies
        run: sh ./cicd/cargo_fetch.sh
      - name: run release build
        run: cargo build --release
      - name: run release tests
        run: cargo test --release
      - name: generate CountryCodes.json
        run: cargo run --example countrycodes --release
      - name: upload release binary
        uses: actions/upload-artifact@v2
        with:
          name: rocketbot-release
          path: |
            target/release/rocketbot
            rocketbot_plugin_calc/data/unitdb.toml
            CountryCodes.json
