[package]
name = "rocketbotweb"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = { version = "0.9" }
hyper = { version = "0.14", features = ["client", "http1", "http2", "server"] }
log = { version = "0.4" }
once_cell = { version = "1.8" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tera = { version = "1.12" }
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7" }
toml = { version = "0.5" }
url = { version = "2.2" }
