[package]
name = "rocketbotweb"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12" }
chrono = { version = "0.4", features = ["serde"] }
ciborium = { version = "0.2" }
env_logger = { version = "0.10" }
form_urlencoded = { version = "1.2" }
hyper = { version = "0.14", features = ["client", "http1", "http2", "server", "tcp"] }
indexmap = { version = "2.0", features = ["serde"] }
log = { version = "0.4" }
once_cell = { version = "1.18" }
png = { version = "0.17" }
regex = { version = "1.9" }
rocketbot_bim_common = { path = "../rocketbot_bim_common" }
rocketbot_date_time = { path = "../rocketbot_date_time" }
rocketbot_string = { path = "../rocketbot_string", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.32", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-serde_json-1"] }
toml = { version = "0.7" }
unicode-normalization = { version = "0.1" }
